import './bootstrap';
import './admin/register'
import './admin/login'
import './admin/dashboard'
import './admin/roomCategory/createRoomCategory'
import './admin/roomCategory/roomCategoryList'
import './admin/roomCategory/viewRoomCategory'
import './admin/room/createRoom'
import './admin/room/roomList'
import './admin/room/viewRoom'
import './admin/guestType'
import './admin/service'

import './user/room'
import './user/roomDatail'
